# fly.toml app configuration file generated for flask-analytics-api

app = "flask-analytics-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_HOST = "0.0.0.0"
  FORCE_SSL = "false"
  REDIS_QUEUE_NAME = "event_queue"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = "tcp"
  internal_port = 8080
  ports = [80, 443]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 900

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "5s"
